# Route
class Route
  def initialize: (?::Station? start_station, ?::Station? end_station) -> void

  def routes: () -> Array[Hash[String, Station]]
  def insert: (Station station) -> Route
  def delete: (Station station) -> Route
end
